version: 2

default: &defaults
  working_directory: ~/angular-google-charts
    docker:
      - image: circleci/node:8-browsers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-.
          # fallback to using the latest cache if no exact match is found
	        - v1-dependencies-

      - run: npm install
      - run: npm run test -- angular-google-charts --watch=false --progress=false

      - save_cache:
          key: v1-dependecies-
          paths:
             - node_modules

      - persist_to_workspace:
          root: ~/angular-google-charts
          paths: .
          
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
        at: ~/angular-google-charts
      - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/angular-google-charts/.npmrc
      - run:
        name: Publish package
        command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/